version: '3'
services:
  todo-rest:
    build: todo-app-backend-springboot/.
    depends_on:
      - todo-db
    ports:
      - 8080:8080
  todo-db:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - 5432:5432
